export const blog_data = [
  {
    id: "001",
    title: "Himalayan Horizons",
    author: "Rajesh Hamal",
    blog: "Join me as I explore the majestic landscapes of Nepal. From trekking in the Himalayas to discovering ancient temples, I'll take you on an enchanting journey through the cultural and natural wonders of this beautiful country.",
    posted_date: "05/28",
  },
  {
    id: "002",
    title: "Hidden Gems of Nepal",
    author: "David Gurung",
    blog: "Unearth the hidden treasures of Nepal with me. I'll guide you through lesser-known destinations, remote villages, and off-the-beaten-path trails, revealing the authentic charm and cultural richness that lie beyond the popular tourist spots.",
    posted_date: "05/28",
  },
  {
    id: "003",
    title: "Kathmandu Chronicles",
    author: "Tom Shrestha",
    blog: "Immerse yourself in the vibrant city of Kathmandu through my eyes. From exploring ancient temples and bustling markets to indulging in delectable local cuisine, I'll share my experiences and tips for navigating Nepal's capital.",
    posted_date: "05/28",
  },
  {
    id: "004",
    title: "Annapurna Adventure",
    author: "Ben Karki",
    blog: "Embark on an unforgettable trek to the Annapurna region of Nepal. Join me as I trek through breathtaking mountain vistas, encounter diverse flora and fauna, and delve into the rich cultural tapestry of the local communities along the way.",
    posted_date: "05/22",
  },
  {
    id: "005",
    title: "Pokhara Paradise",
    author: "Jeniffer Bartaula",
    blog: "Discover the tranquil beauty of Pokhara, Nepal's enchanting lakeside city. From boating on Phewa Lake to paragliding over the Annapurna range, I'll share the best activities, accommodations, and hidden gems in this idyllic destination.",
    posted_date: "09/28",
  },
  {
    id: "006",
    title: "Chitwan Chronicles",
    author: "Ezek Rai",
    blog: "Delve into the wild wonders of Chitwan National Park. Join me on thrilling jungle safaris, spot elusive wildlife, and learn about conservation efforts aimed at preserving the diverse ecosystem of Nepal's renowned national park.",
    posted_date: "05/23",
  },
  {
    id: "007",
    title: "Mustang Mystique",
    author: "Funny Joshi",
    blog: "Embark on a mystical journey to the ancient kingdom of Mustang. From exploring ancient caves and monasteries to witnessing the awe-inspiring landscapes of the Mustang region, I'll unveil the secrets of this extraordinary destination.",
    posted_date: "04/29",
  },
  {
    id: "008",
    title: "Nepal for Adventurers",
    author: "Blake Gupta",
    blog: "Calling all adventure enthusiasts! Join me as we conquer the thrilling rapids of Nepal's rivers, scale towering peaks, and engage in adrenaline-pumping activities like canyoning, mountain biking, and rock climbing.",
    posted_date: "04/28",
  },
  {
    id: "009",
    title: "Sacred Temples of Nepal",
    author: "Niti Gomez",
    blog: "Explore the spiritual side of Nepal as we visit sacred temples and pilgrimage sites. From the revered Pashupatinath Temple to the serene atmosphere of Lumbini, birthplace of Lord Buddha, I'll guide you on a soulful journey.",
    posted_date: "03/28",
  },
  {
    id: "010",
    title: "Nepali Cuisine Delights",
    author: "Manish Smith",
    blog: "Indulge in the flavors of Nepal as I take you on a culinary adventure. From momo-making classes to savoring traditional Newari feasts, join me in discovering the diverse and delicious cuisine that defines Nepali gastronomy.",
    posted_date: "02/28",
  },
];
